# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../laporan/Rancangan/ui/MainWindow-dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import resource_rc


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		# MainWindow.resize(1360, 712)
		# MainWindow.setMinimumSize(QtCore.QSize(1360, 712))
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.top = QtWidgets.QWidget(self.centralwidget)
		self.top.setGeometry(QtCore.QRect(-10, 0, 1381, 51))
		self.top.setStyleSheet(f"background-color: {MainWindow.BGTOP};")
		self.top.setObjectName("top")
		self.LLogo = QtWidgets.QLabel(self.top)
		self.LLogo.setGeometry(QtCore.QRect(10, 0, 231, 51))
		self.LLogo.setStyleSheet("font: 75 20pt \"Arial Black\";\n"
"color: rgb(0, 0, 0);")
		self.LLogo.setText("MIKHOTMAN")
		self.LLogo.setAlignment(QtCore.Qt.AlignCenter)
		self.LLogo.setObjectName("LLogo")
		self.layoutWidget = QtWidgets.QWidget(self.top)
		self.layoutWidget.setGeometry(QtCore.QRect(330, 0, 1041, 51))
		self.layoutWidget.setObjectName("layoutWidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.label_5 = QtWidgets.QLabel(self.layoutWidget)
		self.label_5.setStyleSheet("font: 75 13pt \"Arial Black\";\n"
"color: #000000;")
		self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_5.setObjectName("label_5")
		self.horizontalLayout.addWidget(self.label_5)
		self.LLoginAs = QtWidgets.QLabel(self.layoutWidget)
		self.LLoginAs.setStyleSheet("font: 75 13pt \"Arial Black\";\n"
"color: #000000;")
		self.LLoginAs.setObjectName("LLoginAs")
		self.horizontalLayout.addWidget(self.LLoginAs)
		self.label_6 = QtWidgets.QLabel(self.layoutWidget)
		self.label_6.setStyleSheet("font: 75 13pt \"Arial Black\";\n"
"color: #000000;")
		self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_6.setObjectName("label_6")
		self.horizontalLayout.addWidget(self.label_6)
		self.LRouterName = QtWidgets.QLabel(self.layoutWidget)
		self.LRouterName.setStyleSheet("font: 75 13pt \"Arial Black\";\n"
"color: #000000;")
		self.LRouterName.setObjectName("LRouterName")
		self.horizontalLayout.addWidget(self.LRouterName)
		self.sidebar = QtWidgets.QWidget(self.centralwidget)
		self.sidebar.setGeometry(QtCore.QRect(0, 50, 231, 631))
		self.sidebar.setStyleSheet(f"background-color: {MainWindow.BGSIDEBAR};")
		self.sidebar.setObjectName("sidebar")
		self.btnDashboard = QtWidgets.QPushButton(self.sidebar)
		self.btnDashboard.setGeometry(QtCore.QRect(0, 30, 231, 51))
		self.btnDashboard.setStyleSheet("font: 75 13pt \"Arial Black\";\n"
"text-align: left;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/newPrefix/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		self.btnDashboard.setIcon(icon)
		self.btnDashboard.setIconSize(QtCore.QSize(25, 25))
		self.btnDashboard.setObjectName("btnDashboard")
		self.btnUser = QtWidgets.QPushButton(self.sidebar)
		self.btnUser.setGeometry(QtCore.QRect(0, 90, 231, 51))
		self.btnUser.setStyleSheet("font: 75 13pt \"Arial Black\";\n"
"text-align: left;")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/newPrefix/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		self.btnUser.setIcon(icon1)
		self.btnUser.setIconSize(QtCore.QSize(25, 25))
		self.btnUser.setObjectName("btnUser")
		self.btnUserProfile = QtWidgets.QPushButton(self.sidebar)
		self.btnUserProfile.setGeometry(QtCore.QRect(0, 150, 231, 51))
		self.btnUserProfile.setStyleSheet("font: 75 13pt \"Arial Black\";\n"
"text-align: left;")
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(":/newPrefix/user profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		self.btnUserProfile.setIcon(icon2)
		self.btnUserProfile.setIconSize(QtCore.QSize(25, 25))
		self.btnUserProfile.setObjectName("btnUserProfile")
		self.btnSettings = QtWidgets.QPushButton(self.sidebar)
		self.btnSettings.setGeometry(QtCore.QRect(0, 270, 231, 51))
		self.btnSettings.setStyleSheet("font: 75 13pt \"Arial Black\";\n"
"text-align: left;")
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(":/newPrefix/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		self.btnSettings.setIcon(icon3)
		self.btnSettings.setIconSize(QtCore.QSize(25, 25))
		self.btnSettings.setObjectName("btnSettings")
		self.btnLog = QtWidgets.QPushButton(self.sidebar)
		self.btnLog.setGeometry(QtCore.QRect(0, 330, 231, 51))
		self.btnLog.setStyleSheet("font: 75 13pt \"Arial Black\";\n"
"text-align: left;")
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap(":/newPrefix/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		self.btnLog.setIcon(icon4)
		self.btnLog.setIconSize(QtCore.QSize(25, 25))
		self.btnLog.setObjectName("btnLog")
		self.btnActiveUser = QtWidgets.QPushButton(self.sidebar)
		self.btnActiveUser.setGeometry(QtCore.QRect(0, 210, 231, 51))
		self.btnActiveUser.setStyleSheet("font: 75 13pt \"Arial Black\";\n"
"text-align: left;")
		icon5 = QtGui.QIcon()
		icon5.addPixmap(QtGui.QPixmap(":/newPrefix/multiple-users-silhouette.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		self.btnActiveUser.setIcon(icon5)
		self.btnActiveUser.setIconSize(QtCore.QSize(25, 25))
		self.btnActiveUser.setObjectName("btnActiveUser")
		self.contentview = QtWidgets.QWidget(self.centralwidget)
		self.contentview.setGeometry(QtCore.QRect(230, 50, 1141, 631))
		self.contentview.setStyleSheet(f"background-color: {MainWindow.BGVIEW};")
		self.contentview.setObjectName("contentview")
		self.line = QtWidgets.QFrame(self.contentview)
		self.line.setGeometry(QtCore.QRect(40, 50, 1091, 31))
		self.line.setFrameShape(QtWidgets.QFrame.HLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.LTitle = QtWidgets.QLabel(self.contentview)
		self.LTitle.setGeometry(QtCore.QRect(40, 30, 141, 21))
		self.LTitle.setStyleSheet("font: 75 13pt \"Arial Black\";\n"
"color: #000000;")
		self.LTitle.setObjectName("LTitle")
		self.widget = QtWidgets.QWidget(self.contentview)
		self.widget.setGeometry(QtCore.QRect(40, 210, 491, 331))
		self.widget.setObjectName("widget")
		self.label_3 = QtWidgets.QLabel(self.widget)
		self.label_3.setGeometry(QtCore.QRect(0, 0, 491, 91))
		self.label_3.setStyleSheet("image: url(:/newPrefix/home.png);")
		self.label_3.setText("")
		self.label_3.setObjectName("label_3")
		self.line_2 = QtWidgets.QFrame(self.widget)
		self.line_2.setGeometry(QtCore.QRect(20, 80, 451, 31))
		self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		self.line_3 = QtWidgets.QFrame(self.widget)
		self.line_3.setGeometry(QtCore.QRect(580, 80, 451, 31))
		self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_3.setObjectName("line_3")
		self.label_7 = QtWidgets.QLabel(self.widget)
		self.label_7.setGeometry(QtCore.QRect(20, 130, 101, 17))
		self.label_7.setStyleSheet("text-align:  right;")
		self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.label_7.setObjectName("label_7")
		self.label_8 = QtWidgets.QLabel(self.widget)
		self.label_8.setGeometry(QtCore.QRect(20, 160, 101, 17))
		self.label_8.setStyleSheet("text-align:  right;")
		self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.label_8.setObjectName("label_8")
		self.label_9 = QtWidgets.QLabel(self.widget)
		self.label_9.setGeometry(QtCore.QRect(20, 190, 101, 17))
		self.label_9.setStyleSheet("text-align:  right;")
		self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.label_9.setObjectName("label_9")
		self.label_10 = QtWidgets.QLabel(self.widget)
		self.label_10.setGeometry(QtCore.QRect(20, 220, 101, 17))
		self.label_10.setStyleSheet("text-align:  right;")
		self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.label_10.setObjectName("label_10")
		self.label_16 = QtWidgets.QLabel(self.widget)
		self.label_16.setGeometry(QtCore.QRect(20, 250, 101, 17))
		self.label_16.setStyleSheet("text-align:  right;")
		self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.label_16.setObjectName("label_16")
		self.label_17 = QtWidgets.QLabel(self.widget)
		self.label_17.setGeometry(QtCore.QRect(20, 280, 101, 17))
		self.label_17.setStyleSheet("text-align:  right;")
		self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.label_17.setObjectName("label_17")
		self.LcRouterName = QtWidgets.QLabel(self.widget)
		self.LcRouterName.setGeometry(QtCore.QRect(160, 130, 101, 17))
		self.LcRouterName.setStyleSheet("text-align:  right;")
		self.LcRouterName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.LcRouterName.setObjectName("LcRouterName")
		self.LArsitecture = QtWidgets.QLabel(self.widget)
		self.LArsitecture.setGeometry(QtCore.QRect(160, 160, 101, 17))
		self.LArsitecture.setStyleSheet("text-align:  right;")
		self.LArsitecture.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.LArsitecture.setObjectName("LArsitecture")
		self.LRouterOs = QtWidgets.QLabel(self.widget)
		self.LRouterOs.setGeometry(QtCore.QRect(160, 190, 101, 17))
		self.LRouterOs.setStyleSheet("text-align:  right;")
		self.LRouterOs.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.LRouterOs.setObjectName("LRouterOs")
		self.label_23 = QtWidgets.QLabel(self.widget)
		self.label_23.setGeometry(QtCore.QRect(160, 220, 101, 17))
		self.label_23.setStyleSheet("text-align:  right;")
		self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.label_23.setObjectName("label_23")
		self.LHost = QtWidgets.QLabel(self.widget)
		self.LHost.setGeometry(QtCore.QRect(160, 250, 101, 17))
		self.LHost.setStyleSheet("text-align:  right;")
		self.LHost.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.LHost.setObjectName("LHost")
		self.LcLoginAs = QtWidgets.QLabel(self.widget)
		self.LcLoginAs.setGeometry(QtCore.QRect(160, 280, 101, 17))
		self.LcLoginAs.setStyleSheet("text-align:  right;")
		self.LcLoginAs.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.LcLoginAs.setObjectName("LcLoginAs")
		self.widget_2 = QtWidgets.QWidget(self.contentview)
		self.widget_2.setGeometry(QtCore.QRect(600, 210, 491, 331))
		self.widget_2.setObjectName("widget_2")
		self.label_4 = QtWidgets.QLabel(self.widget_2)
		self.label_4.setGeometry(QtCore.QRect(0, 0, 491, 91))
		self.label_4.setStyleSheet("image: url(:/newPrefix/user.png);")
		self.label_4.setText("")
		self.label_4.setObjectName("label_4")
		self.line_4 = QtWidgets.QFrame(self.widget_2)
		self.line_4.setGeometry(QtCore.QRect(20, 80, 451, 31))
		self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_4.setObjectName("line_4")
		self.label_18 = QtWidgets.QLabel(self.widget_2)
		self.label_18.setGeometry(QtCore.QRect(20, 130, 101, 17))
		self.label_18.setStyleSheet("text-align:  right;")
		self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.label_18.setObjectName("label_18")
		self.label_19 = QtWidgets.QLabel(self.widget_2)
		self.label_19.setGeometry(QtCore.QRect(20, 160, 101, 17))
		self.label_19.setStyleSheet("text-align:  right;")
		self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.label_19.setObjectName("label_19")
		self.LUserTotal = QtWidgets.QLabel(self.widget_2)
		self.LUserTotal.setGeometry(QtCore.QRect(160, 130, 101, 17))
		self.LUserTotal.setStyleSheet("text-align:  right;")
		self.LUserTotal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.LUserTotal.setObjectName("LUserTotal")
		self.LUserTotal_2 = QtWidgets.QLabel(self.widget_2)
		self.LUserTotal_2.setGeometry(QtCore.QRect(160, 160, 101, 17))
		self.LUserTotal_2.setStyleSheet("text-align:  right;")
		self.LUserTotal_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.LUserTotal_2.setObjectName("LUserTotal_2")
		self.label = QtWidgets.QLabel(self.contentview)
		self.label.setGeometry(QtCore.QRect(40, 110, 521, 31))
		self.label.setStyleSheet("font: 75 13pt \"Arial Black\";\n"
"color: #000000;")
		self.label.setObjectName("label")
		self.line.raise_()
		self.LTitle.raise_()
		self.widget.raise_()
		self.label.raise_()
		self.widget_2.raise_()
		MainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MIKHOTMAN | DASHBOARD"))
		self.label_5.setText(_translate("MainWindow", "Login As : "))
		self.label_6.setText(_translate("MainWindow", "Router Name : "))
		self.btnDashboard.setText(_translate("MainWindow", "DASHBOARD"))
		self.btnUser.setText(_translate("MainWindow", "USER"))
		self.btnUserProfile.setText(_translate("MainWindow", "USER PROFILE"))
		self.btnActiveUser.setText(_translate("MainWindow", "ACTIVE USER"))
		self.btnSettings.setText(_translate("MainWindow", "SETTINGS"))
		self.btnLog.setText(_translate("MainWindow", "LOG"))
		self.LTitle.setText(_translate("MainWindow", "DASHBOARD"))
		self.label_7.setText(_translate("MainWindow", "Router Name "))
		self.label_8.setText(_translate("MainWindow", "Arsitecture"))
		self.label_9.setText(_translate("MainWindow", "RouterOs Version"))
		self.label_10.setText(_translate("MainWindow", "license Level"))
		self.label_16.setText(_translate("MainWindow", "Host"))
		self.label_17.setText(_translate("MainWindow", "Login As"))
		self.LRouterName.setText(_translate("MainWindow", MainWindow.ROUTERNAME))
		self.LcRouterName.setText(_translate("MainWindow", MainWindow.ROUTERNAME))
		self.LArsitecture.setText(_translate("MainWindow", MainWindow.ARSITECTURE))
		self.LRouterOs.setText(_translate("MainWindow", MainWindow.VERSION))
		self.label_23.setText(_translate("MainWindow", MainWindow.LLEVEL))
		self.LHost.setText(_translate("MainWindow", MainWindow.HOST))
		self.LLoginAs.setText(_translate("MainWindow", MainWindow.RUSER))
		self.LcLoginAs.setText(_translate("MainWindow", MainWindow.RUSER))
		self.label_18.setText(_translate("MainWindow", "User Total"))
		self.label_19.setText(_translate("MainWindow", "Active User"))
		self.LUserTotal.setText(_translate("MainWindow", f"{MainWindow.TUSER} user(s)"))
		self.LUserTotal_2.setText(_translate("MainWindow", f"{MainWindow.TACTIVEUSER} user(s)"))
		self.label.setText(_translate("MainWindow", f"Welcome to MIKHOTMAN, {MainWindow.RUSER}"))

			


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
